"""Mapping assembler — build YAML config from match results.

Takes scored MatchCandidates and assembles a complete mapping YAML
that follows the same structure as ``person_mapping.yaml``, with
confidence annotations as YAML comments.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from ceds_jsonld.wizard.concept_matcher import MatchCandidate


@dataclass
class WizardResult:
    """Result of a mapping wizard run.

    Attributes:
        mapping_config: The complete YAML-ready mapping dict.
        confidence_report: Per-column match details.
        unmapped_columns: Source columns with no match.
        unmapped_properties: Target properties with no source mapping.
        yaml_text: Pre-formatted YAML string with confidence comments.
    """

    mapping_config: dict[str, Any]
    confidence_report: list[MatchCandidate]
    unmapped_columns: list[str]
    unmapped_properties: list[str]
    yaml_text: str = ""

    def save(self, path: str) -> None:
        """Write the YAML text to a file."""
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(self.yaml_text, encoding="utf-8")


# Confidence tiers for YAML annotation
_TIER_AUTO = 0.90
_TIER_REVIEW = 0.70


def _confidence_marker(conf: float) -> str:
    """Return a confidence marker string for YAML comments."""
    if conf >= _TIER_AUTO:
        return f"# \u2713 {conf:.2f}"
    if conf >= _TIER_REVIEW:
        return f"# ? {conf:.2f} \u2014 REVIEW"
    return f"# \u2717 {conf:.2f} \u2014 LOW CONFIDENCE"


class MappingAssembler:
    """Assemble match results into a valid mapping YAML config.

    Args:
        shape_name: Shape name (e.g. "PersonShape").
        context_url: JSON-LD @context URL.
        base_uri: Base URI prefix for @id values.
    """

    def __init__(
        self,
        shape_name: str,
        context_url: str = "",
        base_uri: str = "",
    ) -> None:
        self._shape_name = shape_name
        self._context_url = context_url
        self._base_uri = base_uri

    def assemble(
        self,
        matches: list[MatchCandidate],
        unmapped_columns: list[str],
        unmapped_properties: list[str],
    ) -> WizardResult:
        """Build a mapping config from match candidates.

        Groups matches by target_shape into the nested properties structure
        expected by FieldMapper.
        """
        by_shape: dict[str, list[MatchCandidate]] = {}
        for m in matches:
            by_shape.setdefault(m.target_shape, []).append(m)

        properties: dict[str, Any] = {}
        for shape_name, shape_matches in by_shape.items():
            prop_key = self._shape_to_property_key(shape_name)
            fields: dict[str, Any] = {}
            for m in shape_matches:
                field_entry: dict[str, Any] = {
                    "source": m.source_column,
                    "target": m.target_property,
                }
                if m.suggested_transform:
                    field_entry["transform"] = m.suggested_transform
                fields[m.target_property] = field_entry
            properties[prop_key] = {
                "type": shape_name,
                "cardinality": "single",
                "fields": fields,
            }

        config: dict[str, Any] = {
            "shape": self._shape_name,
            "context_url": self._context_url,
            "base_uri": self._base_uri,
            "type": self._shape_name.replace("Shape", ""),
            "properties": properties,
        }

        yaml_text = self._build_annotated_yaml(
            config, matches, unmapped_columns, unmapped_properties,
        )

        return WizardResult(
            mapping_config=config,
            confidence_report=matches,
            unmapped_columns=unmapped_columns,
            unmapped_properties=unmapped_properties,
            yaml_text=yaml_text,
        )

    def _shape_to_property_key(self, shape_name: str) -> str:
        """Convert a sub-shape name to its property key."""
        if shape_name.startswith("has"):
            return shape_name
        return f"has{shape_name}"

    def _build_annotated_yaml(
        self,
        config: dict[str, Any],
        matches: list[MatchCandidate],
        unmapped_columns: list[str],
        unmapped_properties: list[str],
    ) -> str:
        """Build YAML text with confidence annotations as comments."""
        lines: list[str] = [
            "# Generated by ceds-jsonld mapping wizard",
            f"# Shape: {self._shape_name}",
            "#",
            "# Confidence Legend:",
            "#   \u2713 = auto-accepted (\u22650.90)",
            "#   ? = review suggested (0.70-0.89)",
            "#   \u2717 = low confidence (<0.70)",
            "#",
        ]
        if unmapped_columns:
            lines.append(f"# Unmapped source columns: {', '.join(unmapped_columns)}")
        if unmapped_properties:
            lines.append(f"# Unmapped target properties: {', '.join(unmapped_properties)}")
        lines.append("")

        yaml_body = yaml.dump(
            config, default_flow_style=False, sort_keys=False, allow_unicode=True,
        )

        match_by_source = {m.source_column: m for m in matches}
        for line in yaml_body.splitlines():
            stripped = line.strip()
            if stripped.startswith("source:"):
                col_name = stripped.split(":", 1)[1].strip().strip("'\"")
                m = match_by_source.get(col_name)
                if m:
                    marker = _confidence_marker(m.confidence)
                    line = f"{line}  {marker}"
            lines.append(line)

        return "\n".join(lines) + "\n"
